### PR TITLE
Onehalfcord

### PR DESCRIPTION
**Pull request by MandeyNel**

### CODE REVIEW

**Comment by frolleks** [comment]
But why

**Comment by MandeyNel** [comment]
merge

**Comment by frolleks** [comment]
all you did was adding a file that has the same thing as the onehalfcord.theme.css file

**Comment by frolleks** [comment]
so i will not merge, sorry about that.

**Review by SammCheese — COMMENTED** [review]
looks good to me

**Comment by rolledev** [comment]
m

**Comment by frolleks** [comment]
gonna merge a .txt file :trollface:

**Comment by Vendicated** [comment]
Plz merge I rely on this patch

**Comment by frolleks** [comment]
:trollface:

**Pull request closed without merging**
